version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: gunicorn MyPortfolio.wsgi:application --bind 0.0.0.0:8000
    container_name: web-app
    env_file:
      - ./.env_data
    depends_on:
      - db
#    ports:
#      - 8000:8000
    expose:
      - 8000 

  nginx:
    build: ./nginx
    ports:
      - 1234:80
    depends_on: 
      - web


  db:
    image: postgres
    volumes:
      - portfolio_db_new:/var/lib/postgresql/data/
    restart: always
    environment:
      - POSTGRES_DB=portfolio
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dbpostgres

volumes:
  portfolio_db_new:
