# Generated by Django 4.0.4 on 2022-05-08 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='CertificateImage',
        ),
    ]
