# Generated by Django 4.0.4 on 2022-05-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_myinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link_web',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
