# Generated by Django 4.0.4 on 2022-05-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_project_link_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateimage',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
